
CREATE TABLE SCORE_INFO (
   STU_NUM INT PRIMARY KEY
   , STU_NAME VARCHAR(50)
   , KOR_SCORE INT
   , ENG_SCORE INT
   , INTRO VARCHAR(100)
);

SELECT * FROM SCORE_INFO;

-- INSERT INTO 테이블명 (컬럼들) VALUES (값들);
INSERT INTO SCORE_INFO
VALUES (2, '홍길동', 80, 90, '반가워요');


-- DELETE FROM 테이블명 [WHERE 조건];
DELETE FROM SCORE_INFO;

-- SELECT 조회할 열 FROM 테이블명 [WHERE 조건];
SELECT STU_NUM, STU_NAME, KOR_SCORE, ENG_SCORE
FROM SCORE_INFO;


