-- 테이블 삭제(데이터 삭제와 구분)
DROP TABLE basic_board; -- 테이블 삭제
DELETE FROM basic_board; -- 데이터 삭제

-- 게시판 프로그램 테이블 생성
CREATE TABLE BASIC_BOARD(
   -- 컬럼명 데이터타입 [제약조건들]
   BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
   , TITLE VARCHAR(50) NOT NULL
   , WRITER VARCHAR(50) NOT NULL
   , CONTENT VARCHAR(100)
   , CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
   , READ_CNT INT DEFAULT 0
);

INSERT INTO basic_board (TITLE, WRITER, CONTENT) 
VALUES ('1', '1', '1');

SELECT * FROM basic_board;

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER)
VALUES (2, '제목', '작성자1');

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT)
VALUES (1, 'BANA', '작성자1', '내용1', '2024-07-01', 5);

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE)
VALUES (5, 'BANANANA', '작성자6', '내용6', '2024-07-01');

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT)
VALUES (2, '제목', '작성자', '내용', '2024-07-01', 3);

DELETE from BASIC_BOARD
WHERE BOARD_NUM = 2;
DELETE from BASIC_BOARD
WHERE BOARD_NUM = 3;

SELECT BOARD_NUM, TITLE, WRITER, CREATE_DATE, READ_CNT
FROM basic_board; 

INSERT INTO basic_board (TITLE, WRITER, CONTENT)
VALUES (2, 2, 'BANANA');

SELECT BOARD_NUM, TITLE, WRITER, CREATE_DATE, READ_CNT
FROM basic_board
WHERE TITLE LIKE '%안녕%';
WHERE WRITER LIKE '%홍%'; 